# Generated by Django 6.0.2 on 2026-03-06 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cassavacharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitronellaCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_growth_habit', models.TextField(blank=True, null=True)),
                ('culm_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('culm_color', models.TextField(blank=True, null=True)),
                ('leaf_sheath_color', models.TextField(blank=True, null=True)),
                ('leaf_blade_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_blade_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_blade_lw_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_blade_color', models.TextField(blank=True, null=True)),
                ('number_of_days_to_flower_initiation', models.IntegerField(blank=True, null=True)),
                ('inflorescence_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inflorescence_type', models.TextField(blank=True, null=True)),
                ('number_of_days_to_seed_maturation', models.IntegerField(blank=True, null=True)),
                ('seed_yield_per_plant_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('characterized_by', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='citronella_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citronella_characteristics', to='core.passportdata')),
            ],
        ),
    ]
