# Generated by Django 6.0.2 on 2026-03-06 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fruitscharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenspurgeCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sowing', models.DateField(blank=True, null=True)),
                ('date_of_planting_at_snap_solution', models.DateField(blank=True, null=True)),
                ('number_of_days_to_germination', models.IntegerField(blank=True, null=True)),
                ('stem_shape', models.TextField(blank=True, null=True)),
                ('diameter_of_main_stem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color_of_stem', models.TextField(blank=True, null=True)),
                ('stem_pubescence', models.TextField(blank=True, null=True)),
                ('leaf_blade_margin', models.TextField(blank=True, null=True)),
                ('leaf_shape', models.TextField(blank=True, null=True)),
                ('leaf_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_color', models.TextField(blank=True, null=True)),
                ('color_of_leaf_veins', models.TextField(blank=True, null=True)),
                ('growth_habit', models.TextField(blank=True, null=True)),
                ('growth_habit_of_stem', models.TextField(blank=True, null=True)),
                ('plant_height_at_first_branching_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_branches_from_the_main_stem', models.IntegerField(blank=True, null=True)),
                ('number_of_internodes', models.IntegerField(blank=True, null=True)),
                ('presence_of_anthocyanin_on_the_leaves', models.TextField(blank=True, null=True)),
                ('intensity_of_anthocyanin_pigmentation_on_the_leaf', models.TextField(blank=True, null=True)),
                ('location_of_anthocyanin_pigmentation_on_the_leaf', models.TextField(blank=True, null=True)),
                ('number_of_days_to_flowering', models.IntegerField(blank=True, null=True)),
                ('diameter_of_umbel_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedicel_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_days_first_harvest', models.IntegerField(blank=True, null=True)),
                ('plant_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gardenspurge_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardenspurge_characteristics', to='core.passportdata')),
            ],
        ),
    ]
