# Generated by Django 6.0.2 on 2026-03-06 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gardenspurgecharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GingerCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_emergence', models.IntegerField(blank=True, null=True)),
                ('leaf_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_shape', models.TextField(blank=True, null=True)),
                ('leaf_pubescence', models.TextField(blank=True, null=True)),
                ('pseudostem_pubescence', models.TextField(blank=True, null=True)),
                ('intensity_of_green_color_of_the_leaves', models.TextField(blank=True, null=True)),
                ('number_of_leaves_per_plant', models.IntegerField(blank=True, null=True)),
                ('days_to_harvest', models.IntegerField(blank=True, null=True)),
                ('plant_height_at_harvest_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('presence_of_anthocyanin_in_one_third_portion_of_the_pseudostem', models.TextField(blank=True, null=True)),
                ('pseudostem_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bud_color', models.TextField(blank=True, null=True)),
                ('number_of_rhizomes_per_plant', models.IntegerField(blank=True, null=True)),
                ('weight_of_rhizomes_per_plant_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_internodes_in_the_rhizome', models.IntegerField(blank=True, null=True)),
                ('rhizome_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rhizome_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rhizome_branching', models.TextField(blank=True, null=True)),
                ('density_of_adventitious_root_on_the_rhizome', models.TextField(blank=True, null=True)),
                ('rhizome_texture_skin', models.TextField(blank=True, null=True)),
                ('rhizome_color_skin', models.TextField(blank=True, null=True)),
                ('easiness_of_peeling_of_the_skin', models.TextField(blank=True, null=True)),
                ('degree_of_fibrousness_of_the_rhizome', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ginger_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ginger_characteristics', to='core.passportdata')),
            ],
        ),
    ]
