# Generated by Django 6.0.2 on 2026-03-06 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gingercharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GotukolaCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_shape', models.TextField(blank=True, null=True)),
                ('leaf_apex_shape', models.TextField(blank=True, null=True)),
                ('leaf_base_shape', models.TextField(blank=True, null=True)),
                ('leaf_base_lobing', models.TextField(blank=True, null=True)),
                ('leaf_margin', models.TextField(blank=True, null=True)),
                ('leaf_color', models.TextField(blank=True, null=True)),
                ('leaf_blade_texture', models.TextField(blank=True, null=True)),
                ('leaf_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_length_over_width_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('petiole_color', models.TextField(blank=True, null=True)),
                ('petiole_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stolon_color', models.TextField(blank=True, null=True)),
                ('stolon_pubescence', models.TextField(blank=True, null=True)),
                ('number_of_flowers_per_umbel', models.IntegerField(blank=True, null=True)),
                ('petal_color', models.TextField(blank=True, null=True)),
                ('bract_color', models.TextField(blank=True, null=True)),
                ('peduncle_color', models.TextField(blank=True, null=True)),
                ('fruit_shape', models.TextField(blank=True, null=True)),
                ('fruit_color', models.TextField(blank=True, null=True)),
                ('fruit_hairiness', models.TextField(blank=True, null=True)),
                ('pedicel_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_surface', models.TextField(blank=True, null=True)),
                ('seed_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_shape', models.TextField(blank=True, null=True)),
                ('hundred_seed_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gotukola_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gotukola_characteristics', to='core.passportdata')),
            ],
        ),
    ]
