# Generated by Django 6.0.2 on 2026-03-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gotukolacharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuavaCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_habit', models.TextField(blank=True, null=True)),
                ('branching_habit', models.TextField(blank=True, null=True)),
                ('branching_density', models.TextField(blank=True, null=True)),
                ('branching_pattern', models.TextField(blank=True, null=True)),
                ('arrangement', models.TextField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('apex_shape', models.TextField(blank=True, null=True)),
                ('base_shape', models.TextField(blank=True, null=True)),
                ('leaf_blade_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_blade_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_size_ratio_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_color', models.TextField(blank=True, null=True)),
                ('petiole_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_upper_surface_pubescence_adaxial', models.TextField(blank=True, null=True)),
                ('leaf_lower_surface_pubescence_abaxial', models.TextField(blank=True, null=True)),
                ('stem_texture', models.TextField(blank=True, null=True)),
                ('stem_color', models.TextField(blank=True, null=True)),
                ('date_of_first_flowering', models.DateField(blank=True, null=True)),
                ('inflorescence_color', models.TextField(blank=True, null=True)),
                ('flower_density', models.TextField(blank=True, null=True)),
                ('inflorescence_structure', models.TextField(blank=True, null=True)),
                ('flower_clustering_habit', models.TextField(blank=True, null=True)),
                ('number_of_years_to_first_fruiting_after_planting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_years_from_flowering_to_maturity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_clustering_habit', models.TextField(blank=True, null=True)),
                ('fruit_shape', models.TextField(blank=True, null=True)),
                ('peduncle_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_surface_texture', models.TextField(blank=True, null=True)),
                ('flesh_color', models.TextField(blank=True, null=True)),
                ('fruit_rind_color', models.TextField(blank=True, null=True)),
                ('number_of_locules', models.IntegerField(blank=True, null=True)),
                ('seed_cavity_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flesh_thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flesh_texture', models.TextField(blank=True, null=True)),
                ('flesh_taste', models.TextField(blank=True, null=True)),
                ('total_soluble_solids_percent_brix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_color', models.TextField(blank=True, null=True)),
                ('seed_shape', models.TextField(blank=True, null=True)),
                ('seed_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hundred_seed_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guava_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guava_characteristics', to='core.passportdata')),
            ],
        ),
    ]
