# Generated by Django 6.0.2 on 2026-03-06 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_jatrophacharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LagundiCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.TextField(blank=True, null=True)),
                ('plant_growth_habit', models.TextField(blank=True, null=True)),
                ('plant_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_span_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stem_diameter_at_base_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branching_habit', models.TextField(blank=True, null=True)),
                ('leaf_growth_habit', models.TextField(blank=True, null=True)),
                ('leaf_base_lobing', models.TextField(blank=True, null=True)),
                ('leaflet_shape', models.TextField(blank=True, null=True)),
                ('leaflet_apex_shape', models.TextField(blank=True, null=True)),
                ('leaflet_base_shape', models.TextField(blank=True, null=True)),
                ('leaflet_margin', models.TextField(blank=True, null=True)),
                ('leaflet_color', models.TextField(blank=True, null=True)),
                ('leaf_pubescence', models.TextField(blank=True, null=True)),
                ('presence_of_leaf_bloom', models.TextField(blank=True, null=True)),
                ('central_leaflet_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('central_leaflet_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lagundi_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lagundi_characteristics', to='core.passportdata')),
            ],
        ),
    ]
