# Generated by Django 6.0.2 on 2026-03-06 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_luffacharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalunggayCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_shape_or_habit', models.TextField(blank=True, null=True)),
                ('tree_nature', models.TextField(blank=True, null=True)),
                ('plant_height_aboveground_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stem_diameter_at_the_base_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branching_habit', models.TextField(blank=True, null=True)),
                ('bark_color_of_mature_tree', models.TextField(blank=True, null=True)),
                ('number_of_branchlets_per_node', models.IntegerField(blank=True, null=True)),
                ('foliage_density', models.TextField(blank=True, null=True)),
                ('leaflet_shape', models.TextField(blank=True, null=True)),
                ('leaflet_apex_shape', models.TextField(blank=True, null=True)),
                ('leaf_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_length_width_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_first_flowering', models.DateField(blank=True, null=True)),
                ('number_of_inflorescence_per_branchlet', models.IntegerField(blank=True, null=True)),
                ('flower_position_on_branchlet', models.TextField(blank=True, null=True)),
                ('nature_of_calyx', models.TextField(blank=True, null=True)),
                ('calyx_color', models.TextField(blank=True, null=True)),
                ('nature_of_corolla', models.TextField(blank=True, null=True)),
                ('corolla_color', models.TextField(blank=True, null=True)),
                ('pink_spots_in_corolla', models.TextField(blank=True, null=True)),
                ('date_of_first_fruit_maturity', models.DateField(blank=True, null=True)),
                ('fruit_maturity', models.TextField(blank=True, null=True)),
                ('fruit_orientation', models.TextField(blank=True, null=True)),
                ('pulp_color', models.TextField(blank=True, null=True)),
                ('number_of_fruits_per_tree', models.IntegerField(blank=True, null=True)),
                ('fruit_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_girth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_longitudinal_ridges_per_fruit', models.IntegerField(blank=True, null=True)),
                ('seed_color', models.TextField(blank=True, null=True)),
                ('seed_shape', models.TextField(blank=True, null=True)),
                ('number_of_seeds_per_fruit', models.IntegerField(blank=True, null=True)),
                ('seed_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hundred_seed_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='malunggay_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malunggay_characteristics', to='core.passportdata')),
            ],
        ),
    ]
