# Generated by Django 6.0.2 on 2026-03-06 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_mungbeancharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeanutCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('days_to_emergence', models.IntegerField(blank=True, null=True)),
                ('plant_growth_habit_pgh', models.TextField(blank=True, null=True)),
                ('branching_pattern', models.TextField(blank=True, null=True)),
                ('stem_pigmentation', models.TextField(blank=True, null=True)),
                ('stem_hairiness', models.TextField(blank=True, null=True)),
                ('lateral_branch_habit', models.TextField(blank=True, null=True)),
                ('main_stem_growth_habit_msgh', models.TextField(blank=True, null=True)),
                ('side_branches_growth_habit_sbgh', models.TextField(blank=True, null=True)),
                ('plant_branching_as_for_1_pbh', models.TextField(blank=True, null=True)),
                ('length_of_reproductive_branch_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_of_maturity_for_curing', models.TextField(blank=True, null=True)),
                ('leaflet_size', models.TextField(blank=True, null=True)),
                ('leaflet_color', models.TextField(blank=True, null=True)),
                ('leaf_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaflet_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaflet_shape', models.TextField(blank=True, null=True)),
                ('hairiness_of_young_leaflets', models.TextField(blank=True, null=True)),
                ('hairiness_of_mature_leaflets', models.TextField(blank=True, null=True)),
                ('days_to_50_percent_flowering', models.IntegerField(blank=True, null=True)),
                ('number_of_flowers_per_inflorescence', models.IntegerField(blank=True, null=True)),
                ('peg_color', models.TextField(blank=True, null=True)),
                ('flowering_general_pattern', models.TextField(blank=True, null=True)),
                ('flowering_pattern_of_main_stem', models.TextField(blank=True, null=True)),
                ('standard_petal_color', models.TextField(blank=True, null=True)),
                ('standard_petal_markings', models.TextField(blank=True, null=True)),
                ('days_to_maturity', models.IntegerField(blank=True, null=True)),
                ('plant_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_constrictions', models.TextField(blank=True, null=True)),
                ('pod_surface_texture', models.TextField(blank=True, null=True)),
                ('pod_reticulation', models.TextField(blank=True, null=True)),
                ('number_of_kernels', models.IntegerField(blank=True, null=True)),
                ('pod_prominence_of_beak', models.TextField(blank=True, null=True)),
                ('pod_shape_of_beak', models.TextField(blank=True, null=True)),
                ('pod_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color_of_uncured_mature_testa', models.TextField(blank=True, null=True)),
                ('color_of_monochromatic_uncured_mature_testa', models.TextField(blank=True, null=True)),
                ('kernel_shape', models.TextField(blank=True, null=True)),
                ('kernel_size', models.TextField(blank=True, null=True)),
                ('number_of_seeds_per_pod', models.IntegerField(blank=True, null=True)),
                ('seed_number_of_colors', models.TextField(blank=True, null=True)),
                ('primary_dried_seed_color', models.TextField(blank=True, null=True)),
                ('secondary_dried_seed_color', models.TextField(blank=True, null=True)),
                ('seed_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_pods_per_plant', models.IntegerField(blank=True, null=True)),
                ('yield_per_plant_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_of_ten_pods_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_of_first_harvest_over_total_harvest_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hundred_seed_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='peanut_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peanut_characteristics', to='core.passportdata')),
            ],
        ),
    ]
