# Generated by Django 6.0.2 on 2026-03-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_peppercharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PigeonpeaCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('transplanting_date', models.DateField(blank=True, null=True)),
                ('hypocotyl_color', models.TextField(blank=True, null=True)),
                ('hypocotyl_color_intensity', models.TextField(blank=True, null=True)),
                ('cotyledonous_leaf_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotyledonous_leaf_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotyledonous_leaf_shape', models.TextField(blank=True, null=True)),
                ('cotyledonous_leaf_color', models.TextField(blank=True, null=True)),
                ('hypocotyl_pubescence', models.TextField(blank=True, null=True)),
                ('days_to_emergence', models.IntegerField(blank=True, null=True)),
                ('plant_growth_habit', models.TextField(blank=True, null=True)),
                ('growth_pattern', models.TextField(blank=True, null=True)),
                ('attachment_of_primary_leaves', models.TextField(blank=True, null=True)),
                ('primary_leaf_shape', models.TextField(blank=True, null=True)),
                ('leaf_color', models.TextField(blank=True, null=True)),
                ('leaf_pubescence', models.TextField(blank=True, null=True)),
                ('terminal_leaflet_shape', models.TextField(blank=True, null=True)),
                ('terminal_leaflet_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leafiness', models.TextField(blank=True, null=True)),
                ('petiole_color', models.TextField(blank=True, null=True)),
                ('stem_color', models.TextField(blank=True, null=True)),
                ('days_to_75_percent_maturity', models.IntegerField(blank=True, null=True)),
                ('plant_height_at_maturity_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branching_orientation', models.TextField(blank=True, null=True)),
                ('diameter_of_canopy_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_to_50_percent_flowering', models.IntegerField(blank=True, null=True)),
                ('raceme_position', models.TextField(blank=True, null=True)),
                ('raceme_number', models.IntegerField(blank=True, null=True)),
                ('flowering_pattern', models.TextField(blank=True, null=True)),
                ('flower_main_color', models.TextField(blank=True, null=True)),
                ('second_flower_color', models.TextField(blank=True, null=True)),
                ('pattern_of_streaks', models.TextField(blank=True, null=True)),
                ('pod_bearing_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_color_at_immature_stage', models.TextField(blank=True, null=True)),
                ('attachment_of_mature_pod_to_peduncle', models.TextField(blank=True, null=True)),
                ('pod_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_pubescence', models.TextField(blank=True, null=True)),
                ('constriction_of_pod_between_seeds', models.TextField(blank=True, null=True)),
                ('pod_curvature', models.TextField(blank=True, null=True)),
                ('pod_beak_shape', models.TextField(blank=True, null=True)),
                ('dry_pod_color', models.TextField(blank=True, null=True)),
                ('seed_color_pattern', models.TextField(blank=True, null=True)),
                ('seed_main_color', models.TextField(blank=True, null=True)),
                ('seed_second_color', models.TextField(blank=True, null=True)),
                ('mature_seed_color', models.TextField(blank=True, null=True)),
                ('eye_color', models.TextField(blank=True, null=True)),
                ('eye_size', models.TextField(blank=True, null=True)),
                ('seed_shape', models.TextField(blank=True, null=True)),
                ('hilum', models.TextField(blank=True, null=True)),
                ('seed_number_per_pod', models.IntegerField(blank=True, null=True)),
                ('hundred_seed_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pigeonpea_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pigeonpea_characteristics', to='core.passportdata')),
            ],
        ),
    ]
