# Generated by Django 6.0.2 on 2026-03-06 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_ricebeancharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabilaCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_suckers_per_plant_pcs', models.IntegerField(blank=True, null=True)),
                ('spine_frequency_per_10_cm_length_of_leaf_pcs', models.IntegerField(blank=True, null=True)),
                ('spine_base_color', models.TextField(blank=True, null=True)),
                ('spine_tip_color', models.TextField(blank=True, null=True)),
                ('spine_tip_nature', models.TextField(blank=True, null=True)),
                ('intensity_of_green_color_in_leaf_adaxial', models.TextField(blank=True, null=True)),
                ('intensity_of_green_color_in_leaf_abaxial', models.TextField(blank=True, null=True)),
                ('leaf_spots_presence', models.TextField(blank=True, null=True)),
                ('leaf_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_length_width_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_first_flowering', models.DateField(blank=True, null=True)),
                ('number_of_inflorescence_per_plant_pcs', models.IntegerField(blank=True, null=True)),
                ('inflorescence_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_flowers_per_inflorescence_pcs', models.IntegerField(blank=True, null=True)),
                ('flower_color', models.TextField(blank=True, null=True)),
                ('flower_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fruit_setting', models.TextField(blank=True, null=True)),
                ('number_of_fruits_per_inflorescence_pcs', models.IntegerField(blank=True, null=True)),
                ('immature_fruit_color', models.TextField(blank=True, null=True)),
                ('mature_fruit_color', models.TextField(blank=True, null=True)),
                ('number_of_seeds_per_fruit_pcs', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sabila_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabila_characteristics', to='core.passportdata')),
            ],
        ),
    ]
