# Generated by Django 6.0.2 on 2026-03-06 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sabilacharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SambongCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height_aboveground_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stem_hairiness', models.TextField(blank=True, null=True)),
                ('internode_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stem_diameter_at_the_base_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_shape', models.TextField(blank=True, null=True)),
                ('leaf_apex', models.TextField(blank=True, null=True)),
                ('leaf_base', models.TextField(blank=True, null=True)),
                ('leaf_margin', models.TextField(blank=True, null=True)),
                ('leaf_color', models.TextField(blank=True, null=True)),
                ('leaf_blade_texture', models.TextField(blank=True, null=True)),
                ('presence_of_leaf_stipules', models.TextField(blank=True, null=True)),
                ('number_of_stipules', models.IntegerField(blank=True, null=True)),
                ('location_of_first_stipule', models.TextField(blank=True, null=True)),
                ('leaf_attachment_to_stem', models.TextField(blank=True, null=True)),
                ('leaf_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_length_width_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_first_flowering', models.DateField(blank=True, null=True)),
                ('flower_color', models.TextField(blank=True, null=True)),
                ('seed_color', models.TextField(blank=True, null=True)),
                ('pappus_color', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sambong_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sambong_characteristics', to='core.passportdata')),
            ],
        ),
    ]
