# Generated by Django 6.0.2 on 2026-03-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_sambongcharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapbeanCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.TextField(blank=True, null=True)),
                ('date_planted', models.DateField(blank=True, null=True)),
                ('days_to_emergence', models.IntegerField(blank=True, null=True)),
                ('emerging_cotyledon_color', models.TextField(blank=True, null=True)),
                ('hypocotyl_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hypocotyl_pigmentation', models.TextField(blank=True, null=True)),
                ('leaf_shape', models.TextField(blank=True, null=True)),
                ('growth_pattern', models.TextField(blank=True, null=True)),
                ('leaflet_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stem_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_to_flowering', models.IntegerField(blank=True, null=True)),
                ('number_of_nodes_on_main_stem_from_the_base_to_the_first', models.IntegerField(blank=True, null=True)),
                ('flower_buds_per_inflorescence', models.IntegerField(blank=True, null=True)),
                ('color_of_standard', models.TextField(blank=True, null=True)),
                ('wing_opening', models.TextField(blank=True, null=True)),
                ('colour_of_flower_wings', models.TextField(blank=True, null=True)),
                ('duration_of_flowering', models.TextField(blank=True, null=True)),
                ('pod_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_cross_section', models.TextField(blank=True, null=True)),
                ('pod_suture_string', models.TextField(blank=True, null=True)),
                ('pod_color_at_physiological_maturity', models.TextField(blank=True, null=True)),
                ('pod_wall_fiber', models.TextField(blank=True, null=True)),
                ('locules_per_pod', models.IntegerField(blank=True, null=True)),
                ('pod_curvature_of_fully_expanded_immature_pod', models.TextField(blank=True, null=True)),
                ('days_to_first_mature', models.IntegerField(blank=True, null=True)),
                ('mature_pod_colour', models.TextField(blank=True, null=True)),
                ('number_of_locules_per_pod', models.IntegerField(blank=True, null=True)),
                ('pod_beak_orientation', models.TextField(blank=True, null=True)),
                ('pod_beak_position', models.TextField(blank=True, null=True)),
                ('pod_dehiscence', models.TextField(blank=True, null=True)),
                ('seed_shape', models.TextField(blank=True, null=True)),
                ('background_colour', models.TextField(blank=True, null=True)),
                ('seed_coat_pattern', models.TextField(blank=True, null=True)),
                ('seed_darker_color', models.TextField(blank=True, null=True)),
                ('seed_coat_lighter_colour', models.TextField(blank=True, null=True)),
                ('briliance_of_seed', models.TextField(blank=True, null=True)),
                ('pattern_colour', models.TextField(blank=True, null=True)),
                ('second_pattern_colour', models.TextField(blank=True, null=True)),
                ('seed_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='snapbean_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapbean_characteristics', to='core.passportdata')),
            ],
        ),
    ]
