# Generated by Django 6.0.2 on 2026-03-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_snapbeancharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoybeanCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.TextField(blank=True, null=True)),
                ('date_planted', models.DateField(blank=True, null=True)),
                ('days_to_emergence', models.IntegerField(blank=True, null=True)),
                ('seedling_vigor', models.TextField(blank=True, null=True)),
                ('hypocotyl_color', models.TextField(blank=True, null=True)),
                ('hypocotyl_intensity_of_coloration', models.TextField(blank=True, null=True)),
                ('leaflet_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaflet_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaflet_size', models.TextField(blank=True, null=True)),
                ('number_of_leaflets', models.IntegerField(blank=True, null=True)),
                ('plant_growth_type', models.TextField(blank=True, null=True)),
                ('plant_growth_habit', models.TextField(blank=True, null=True)),
                ('plant_color_of_hairs_on_the_main_stem', models.TextField(blank=True, null=True)),
                ('petiole_presence', models.TextField(blank=True, null=True)),
                ('leaf_blistering', models.TextField(blank=True, null=True)),
                ('leaf_shape_of_lateral_leaflet', models.TextField(blank=True, null=True)),
                ('leaf_intensity_of_green_color', models.TextField(blank=True, null=True)),
                ('pubescence', models.TextField(blank=True, null=True)),
                ('pubescence_density', models.TextField(blank=True, null=True)),
                ('pubescence_color', models.TextField(blank=True, null=True)),
                ('days_to_50_percent_flowering', models.IntegerField(blank=True, null=True)),
                ('flower_keel_color', models.TextField(blank=True, null=True)),
                ('flower_standard_color', models.TextField(blank=True, null=True)),
                ('flower_wing_color', models.TextField(blank=True, null=True)),
                ('days_to_first_mature_pods', models.IntegerField(blank=True, null=True)),
                ('mature_pod_color', models.TextField(blank=True, null=True)),
                ('pod_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_coat_color', models.TextField(blank=True, null=True)),
                ('seed_coat_pattern', models.TextField(blank=True, null=True)),
                ('hilum_color', models.TextField(blank=True, null=True)),
                ('seed_coat_surface_luster', models.TextField(blank=True, null=True)),
                ('strophiole_at_the_hilum', models.TextField(blank=True, null=True)),
                ('cotyledon_color', models.TextField(blank=True, null=True)),
                ('seed_shape', models.TextField(blank=True, null=True)),
                ('ground_color_of_testa', models.TextField(blank=True, null=True)),
                ('coloration_due_to_peroxidase_activity_in_seed_coat', models.TextField(blank=True, null=True)),
                ('color_of_hilum_funicle', models.TextField(blank=True, null=True)),
                ('number_of_pods_per_plant', models.IntegerField(blank=True, null=True)),
                ('yield_per_plant_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ten_pod_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_seeds_per_pod', models.IntegerField(blank=True, null=True)),
                ('percentage_of_first_harvest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hundred_seed_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='soybean_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soybean_characteristics', to='core.passportdata')),
            ],
        ),
    ]
