# Generated by Django 6.0.2 on 2026-03-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_tomatocharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmericCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_emergence', models.IntegerField(blank=True, null=True)),
                ('plant_height_at_harvest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('basal_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pseudostem_pubescence', models.TextField(blank=True, null=True)),
                ('leaf_pubescence', models.TextField(blank=True, null=True)),
                ('prominence_of_leaf_venation', models.TextField(blank=True, null=True)),
                ('spatial_arrangement_of_leaf_veins', models.TextField(blank=True, null=True)),
                ('plicate_of_leaves', models.TextField(blank=True, null=True)),
                ('intensity_of_green_color_in_ventral_leaf', models.TextField(blank=True, null=True)),
                ('intensity_of_green_color_in_dorsal_leaf', models.TextField(blank=True, null=True)),
                ('number_of_leaves_per_plant_pcs', models.IntegerField(blank=True, null=True)),
                ('length_of_petiole_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_of_leaf_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_of_leaf_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_length_width_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_of_first_flowering_from_planting', models.IntegerField(blank=True, null=True)),
                ('flower_color', models.TextField(blank=True, null=True)),
                ('length_of_peduncle_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_of_infloresence_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_to_harvest_from_planting', models.IntegerField(blank=True, null=True)),
                ('overall_shape_of_rhizome', models.TextField(blank=True, null=True)),
                ('density_of_adventitious_root_on_the_rhizome', models.TextField(blank=True, null=True)),
                ('number_of_rhizomes_per_plant_pcs', models.IntegerField(blank=True, null=True)),
                ('number_of_internodes_per_rhizome_pcs', models.IntegerField(blank=True, null=True)),
                ('weight_of_rhizome_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_of_rhizome_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diameter_of_rhizome_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_fingers_per_rhizome_pcs', models.IntegerField(blank=True, null=True)),
                ('length_of_fingers_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diameter_of_fingers_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fresh_color_of_rhizomes', models.TextField(blank=True, null=True)),
                ('organoleptic_aroma_of_rhizomes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='turmeric_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmeric_characteristics', to='core.passportdata')),
            ],
        ),
    ]
