# Generated by Django 6.0.2 on 2026-03-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_turmericcharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WingedbeanCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.TextField(blank=True, null=True)),
                ('date_planted', models.DateField(blank=True, null=True)),
                ('days_to_emergence', models.IntegerField(blank=True, null=True)),
                ('hypocotyl_color', models.TextField(blank=True, null=True)),
                ('hypocotyl_color_intensity', models.TextField(blank=True, null=True)),
                ('hypocotyl_pubescence', models.TextField(blank=True, null=True)),
                ('hypocotyl_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_growth', models.TextField(blank=True, null=True)),
                ('leaflet_size', models.TextField(blank=True, null=True)),
                ('leaflet_shape', models.TextField(blank=True, null=True)),
                ('stem_color', models.TextField(blank=True, null=True)),
                ('presence_of_tuber', models.TextField(blank=True, null=True)),
                ('tuber_size', models.TextField(blank=True, null=True)),
                ('calyx_colour', models.TextField(blank=True, null=True)),
                ('corolla_colour_of_wings_and_standard', models.TextField(blank=True, null=True)),
                ('pod_colour', models.TextField(blank=True, null=True)),
                ('presence_of_pod_specks', models.TextField(blank=True, null=True)),
                ('pod_wing_colour', models.TextField(blank=True, null=True)),
                ('pod_surface_texture', models.TextField(blank=True, null=True)),
                ('pod_shape', models.TextField(blank=True, null=True)),
                ('pod_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pod_shattering', models.TextField(blank=True, null=True)),
                ('seed_colour', models.TextField(blank=True, null=True)),
                ('presence_of_seed_mottling', models.TextField(blank=True, null=True)),
                ('hilum_colour', models.TextField(blank=True, null=True)),
                ('seed_shape', models.TextField(blank=True, null=True)),
                ('seed_surface', models.TextField(blank=True, null=True)),
                ('number_of_seeds_per_pod', models.IntegerField(blank=True, null=True)),
                ('hundred_seed_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wingedbean_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wingedbean_characteristics', to='core.passportdata')),
            ],
        ),
    ]
