# Generated by Django 6.0.2 on 2026-03-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_xanthosomacharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='YamCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigor', models.TextField(blank=True, null=True)),
                ('stem_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stem_color', models.TextField(blank=True, null=True)),
                ('number_of_internodes_to_first_branching', models.IntegerField(blank=True, null=True)),
                ('internode_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('absence_or_presence_of_waxiness', models.TextField(blank=True, null=True)),
                ('wing_size', models.TextField(blank=True, null=True)),
                ('wing_color', models.TextField(blank=True, null=True)),
                ('spines_on_stem_base', models.TextField(blank=True, null=True)),
                ('position_of_leaves', models.TextField(blank=True, null=True)),
                ('leaf_density', models.TextField(blank=True, null=True)),
                ('leaf_color', models.TextField(blank=True, null=True)),
                ('leaf_vein_color_upper_surface', models.TextField(blank=True, null=True)),
                ('leaf_vein_color_lower_surface', models.TextField(blank=True, null=True)),
                ('leaf_margin_color', models.TextField(blank=True, null=True)),
                ('leaf_shape', models.TextField(blank=True, null=True)),
                ('distance_between_lobes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position_of_the_widest_part_of_the_leaf', models.TextField(blank=True, null=True)),
                ('tip_color', models.TextField(blank=True, null=True)),
                ('petiole_color', models.TextField(blank=True, null=True)),
                ('absence_or_presence_of_stipules', models.TextField(blank=True, null=True)),
                ('absence_or_presence_of_aerial_tubers', models.TextField(blank=True, null=True)),
                ('aerial_tuber_shape', models.TextField(blank=True, null=True)),
                ('skin_color', models.TextField(blank=True, null=True)),
                ('surface_texture', models.TextField(blank=True, null=True)),
                ('flesh_color', models.TextField(blank=True, null=True)),
                ('number_of_tubers_per_hill', models.IntegerField(blank=True, null=True)),
                ('relationship_of_tubers', models.TextField(blank=True, null=True)),
                ('absence_or_presence_of_corms', models.TextField(blank=True, null=True)),
                ('corm_size', models.TextField(blank=True, null=True)),
                ('sprouting_at_harvest', models.TextField(blank=True, null=True)),
                ('tuber_shape', models.TextField(blank=True, null=True)),
                ('tendency_of_tuber_to_branch', models.TextField(blank=True, null=True)),
                ('place_where_tuber_branches', models.TextField(blank=True, null=True)),
                ('tuber_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuber_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roots_on_the_tuber_surface', models.TextField(blank=True, null=True)),
                ('place_of_roots_on_the_tuber', models.TextField(blank=True, null=True)),
                ('absence_or_presence_of_cracks_on_the_tuber_surface', models.TextField(blank=True, null=True)),
                ('tuber_skin_thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuber_skin_color_beneath_the_bark', models.TextField(blank=True, null=True)),
                ('hardness_of_tuber', models.TextField(blank=True, null=True)),
                ('skin_color_at_head_of_the_tuber', models.TextField(blank=True, null=True)),
                ('flesh_color_at_central_transverse_cross_section', models.TextField(blank=True, null=True)),
                ('flesh_color_at_lower_part_of_tuber', models.TextField(blank=True, null=True)),
                ('uniformity_of_flesh_color_in_cross_section', models.TextField(blank=True, null=True)),
                ('texture_of_flesh', models.TextField(blank=True, null=True)),
                ('time_for_flesh_oxidation_after_cutting', models.TextField(blank=True, null=True)),
                ('flesh_oxidation_color', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='yam_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yam_characteristics', to='core.passportdata')),
            ],
        ),
    ]
