# Generated by Django 6.0.2 on 2026-03-06 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_yamcharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='YerbabuenaCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_growth_habit', models.TextField(blank=True, null=True)),
                ('branching_density', models.TextField(blank=True, null=True)),
                ('stem_color', models.TextField(blank=True, null=True)),
                ('stem_hairiness', models.TextField(blank=True, null=True)),
                ('stem_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_shape', models.TextField(blank=True, null=True)),
                ('leaf_apex_shape', models.TextField(blank=True, null=True)),
                ('leaf_base_shape', models.TextField(blank=True, null=True)),
                ('leaf_blade_color', models.TextField(blank=True, null=True)),
                ('pubescence_density_of_upper_adaxial_leaf_surface', models.TextField(blank=True, null=True)),
                ('leaf_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leaf_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_first_flowering_from_planting', models.DateField(blank=True, null=True)),
                ('corolla_color', models.TextField(blank=True, null=True)),
                ('shape_of_calyx', models.TextField(blank=True, null=True)),
                ('pubescence_density_of_corolla', models.TextField(blank=True, null=True)),
                ('seed_color', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='yerbabuena_characteristics/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yerbabuena_characteristics', to='core.passportdata')),
            ],
        ),
    ]
