# Generated by Django 6.0.2 on 2026-03-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_yerbabuenacharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompiledCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.TextField(blank=True, null=True)),
                ('source_model', models.CharField(max_length=120)),
                ('source_id', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('passportData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compiled_characteristics', to='core.passportdata')),
            ],
            options={
                'indexes': [models.Index(fields=['crop_name'], name='core_compil_crop_na_bee171_idx'), models.Index(fields=['source_model'], name='core_compil_source__dcaccf_idx'), models.Index(fields=['source_id'], name='core_compil_source__b1fff2_idx'), models.Index(fields=['passportData'], name='core_compil_passpor_2ab8f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_model', 'source_id'), name='unique_compiled_characteristic_source')],
            },
        ),
    ]
